# majority adapt from https://dev.to/moaaz_adel/github-actions-a-simple-way-to-trigger-workflow-from-another-workflow-1b55
name: Trigger OpenStudio Standards GitHub Action to Update Data
run-name: ${{github.actor}} is triggering GitHub Action in OSSTD
on: [push] # to be modified later with PR merge
jobs:
  trigger-osstd-update:
    name: Trigger OpenStudio GitHub Action to initiate a PR there with data update pulling data from here.
    runs-on: 'ubuntu-latest'
    steps:
        - name: GitHub API POST
          run: |
            curl -X POST https://api.github.com/repos/NREL/openstudio-standards/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.JERRY_ACTIONS_KEY }} \
            --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

# below from https://github.com/marketplace/actions/repository-dispatch
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v2
          with:
            token: ${{ secrets.JERRY_ACTIONS_KEY }}
            repository: NREL/openstudio-standards
            event-type: my-event
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'